DROP TABLE IF EXISTS song_tags;
DROP TABLE IF EXISTS collection_songs;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS collections;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS genres;
