package beatbinder.persistence;

import java.util.List;

import beatbinder.exceptions.DuplicateTagException;
import beatbinder.exceptions.TagNotFoundException;
import beatbinder.objects.Tag;

/**
 * Interface for interacting with the {@link Tag} aspect of the database.
 * Contains CRUD functionality, as well as accessing focused groups of data.
 */
public interface ITagPersistence {
    /**
     * Inserts the given {@link Tag} instance into the database. The ID given with {@code tag} is
     * replaced by one generated by the database.
     * 
     * @param tag the {@link Tag} to insert.
     * @return the inserted {@link Tag}.
     * @throws DuplicateTagException if {@code tag} is already present in the database.
     */
    public Tag createTag(Tag tag);
    
    /**
     * Removes the given {@link Tag} instance from the database.
     * 
     * @param tag the {@link Tag} to delete.
     * @return the deleted {@link Tag}.
     * @throws TagNotFoundException if {@code tag} is not found in the database.
     */
    public Tag deleteTag(Tag tag);
    
    /**
     * Retrieves a {@link Tag} instance from the database by its unique ID.
     * 
     * @param id the ID of the {@link Tag} to return.
     * @return the {@link Tag} with ID = {@code id}.
     * @throws TagNotFoundException if a {@link Tag} with {@code id} is not found in the database.
     */
    public Tag getTagByID(int id);
    
    /**
     * Replaces a {@link Tag} instance in the database with the new given {@code tag}.
     * 
     * @param tag the new {@link Tag}.
     * @return the new {@link Tag}.
     * @throws TagNotFoundException if a matching {@link Tag} is not found in the database.
     */
    public Tag updateTag(Tag tag);
    

    
    /**
     * Adds a tag with the given {@code tagID} to the song with the given {@code songID}.
     * 
     * Returned tag instances are unordered.
     * 
     * @param tagID the ID of the tag to add.
     * @param songID the ID of the song to tag.
     * @return a list of {@link Tag} instances associated with the song after the addition.
     * @throws TagNotFoundException if a tag with {@code tagID} is not found.
     */
    public List<Tag> addTagToSong(int tagID, int songID);

    /**
     * Deletes a tag with the given {@code tagID} from the song with the given {@code songID}.
     * 
     * Returned tag instances are unordered.
     * 
     * @param tagID the ID of the tag to delete.
     * @param songID the ID of the song to delete the tag from.
     * @return a list of {@link Tag} instances associated with the song after the deletion.
     * @throws TagNotFoundException if a tag with {@code tagID} is not found.
     */
    public List<Tag> deleteTagFromSong(int tagID, int songID);



    /**
     * Retrieves all {@link Tag} instances in the database with no order.
     * 
     * @return all {@link Tag} instances.
     */
    public List<Tag> getAllTags();

    /**
     * Retrieves all song IDs associated with the tag associated with {@code tagID}.
     * 
     * Returned song IDs have no order.
     * 
     * @param tagID the ID of the tag.
     * @return all Song IDs associated with the tag with {@code tagID}.
     * @throws TagNotFoundException if a tag with {@code tagID} is not found.
     */
    public List<Integer> getSongIdsByTag(int tagID);

    /**
     * Retrieves all {@link Tag} instances associated with the song with ID {@code songID}.
     * 
     * Returned tags have no order.
     * 
     * @param songID the ID of the song to get the tags of.
     * @return a list of {@link Tag} instances associated with the song.
     */
    public List<Tag> getTagsOfSong(int songID); // get all Tags attached to a song
}
